[package]
name = "advent-of-code-23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "*"
lazy_static = "1.4"
regex = "*"
itertools = "*"
num = "*"
